# Generated by Django 5.2.17 on 2026-09-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('catalog', '0005_workflowsteptemplate_requires_review_to_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='cases_applicable', to='catalog.documentcategory'),
        ),
        migrations.AddField(
            model_name='case',
            name='documents_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
