# Generated by Django 5.2.16 on 2026-07-13 05:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'DIY'), (2, 'Enhanced'), (3, 'Full Service')], unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attorney_minutes', models.PositiveIntegerField(default=0)),
                ('includes_document_review', models.BooleanField(default=False)),
                ('includes_interview_coaching', models.BooleanField(default=False)),
                ('includes_representation', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('allows_multiple', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='catalog.applicationtype')),
            ],
            options={
                'verbose_name_plural': 'document categories',
                'ordering': ['application_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='catalog.applicationtype')),
            ],
            options={
                'ordering': ['application_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('single', 'Single choice'), ('multi', 'Multiple choice'), ('boolean', 'Yes / No'), ('text', 'Short text')], default='single', max_length=10)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.questionnaire')),
            ],
            options={
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_disqualifying', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.question')),
                ('skip_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='catalog.applicationtype')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='catalog.tier')),
            ],
            options={
                'ordering': ['application_type', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_document_gate', models.BooleanField(default=False)),
                ('firm_performed_for_full_service', models.BooleanField(default=False)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='catalog.applicationtype')),
            ],
            options={
                'ordering': ['application_type', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('application_type', 'version'), name='unique_questionnaire_version'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('application_type', 'tier'), name='unique_package'),
        ),
        migrations.AddConstraint(
            model_name='workflowsteptemplate',
            constraint=models.UniqueConstraint(fields=('application_type', 'order'), name='unique_step_order'),
        ),
    ]
