# Generated by Django 5.2.16 on 2026-07-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='flag_strength',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='is_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='recommends_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.tier'),
        ),
    ]
