# Generated by Django 5.2.16 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_questionoption_flag_strength_questionoption_is_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='stop_message',
            field=models.TextField(blank=True, help_text='Shown to the visitor when this disqualifying answer ends the quiz.'),
        ),
    ]
