# Generated by Django 5.2.16 on 2026-08-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_questionoption_stop_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='attorney_minutes',
        ),
        migrations.AddField(
            model_name='package',
            name='installment_amount_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='installments_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='included_meetings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tier',
            name='meetings_note',
            field=models.CharField(blank=True, default='Up to 1 hour per meeting', max_length=100),
        ),
        migrations.AlterField(
            model_name='tier',
            name='level',
            field=models.IntegerField(choices=[(1, 'DIY'), (2, 'Attorney Review'), (3, 'Enhanced'), (4, 'Full Service')], unique=True),
        ),
    ]
