# Generated by Django 5.2.17 on 2026-09-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_tier_attorney_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='requires_review_to_unlock',
            field=models.BooleanField(default=False),
        ),
    ]
