# Generated by Django 5.2.17 on 2026-09-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_workflowsteptemplate_requires_review_to_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='requires_attorney_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
