# Generated by Django 5.2.17 on 2026-09-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_workflowsteptemplate_requires_attorney_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='body',
            field=models.TextField(blank=True, help_text='Long-form guidance for the step detail page. Supports Django template tags referencing `case` (e.g. {% if case.package.tier.includes_representation %}).'),
        ),
        migrations.CreateModel(
            name='ResourceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_cards', to='catalog.workflowsteptemplate')),
            ],
            options={
                'ordering': ['step', 'order'],
            },
        ),
    ]
